on : push
jobs :
     last-job:
        runs-on : windows-latest
        steps :
          - run : node --version
          - uses : actions/checkout@v3
          - run : npm ci
          - run : node index.js
          - run : npx eslint .